#pragma config(Motor,  port2,           forklift,      tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port4,           left,          tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           right,         tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port7,           ptsd2,         tmotorServoStandard, openLoop, reversed)
#pragma config(Motor,  port8,           ptsd,          tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//This code probably works

// Automatically Generated Autonomous Task Code
int autoTaskLength = 231;
string eventsList[231] = {"L", "L", "L", "R", "L", "R", "L", "L", "L", "L", "R", "L", "R", "R", "L", "R", "R", "L", "R", "R", "R", "R", "R", "R", "R", "L", "R", "R", "L", "R", "R", "R", "R", "L", "R", "L", "R", "R", "R", "L", "R", "R", "R", "R", "R", "R", "L", "R", "L", "L", "R", "L", "L", "R", "L", "R", "L", "L", "R", "L", "R", "L", "R", "L", "L", "R", "L", "R", "L", "R", "L", "L", "R", "L", "L", "R", "L", "L", "L", "L", "R", "L", "L", "R", "L", "R", "L", "R", "R", "L", "R", "L", "R", "R", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "L", "R", "R", "R", "L", "R", "R", "R", "R", "R", "R", "R", "R", "R", "R", "R", "R", "R", "R", "R", "R", "L", "R", "R", "R", "R", "L", "L", "R", "R", "R", "L", "R", "R", "L", "L", "R", "R", "R", "L", "R", "L", "R", "R", "R", "R", "L", "L", "R", "L", "R", "L", "R", "L", "R", "L", "R", "L", "R", "L", "L", "R", "L", "L", "R", "L", "R", "L", "R", "R", "L", "R", "R", "L", "L", "R", "L", "L", "R", "R", "L"};
int timingList[231] = {220, 260, 350, 350, 410, 410, 430, 470, 700, 760, 760, 820, 970, 1060, 1180, 1180, 1190, 1250, 1250, 1270, 1340, 1390, 1400, 1460, 1480, 1520, 1520, 1540, 1600, 1600, 1690, 1730, 1760, 1820, 1910, 2180, 2500, 2540, 2560, 2620, 2620, 2630, 2690, 2710, 2770, 2830, 2900, 2900, 2920, 2980, 2980, 3070, 3160, 3160, 3200, 3200, 3260, 3310, 3310, 3340, 3340, 3400, 3400, 3460, 3470, 3470, 3560, 3560, 3590, 3590, 3610, 3670, 3670, 3680, 3740, 3740, 3760, 3800, 3820, 3890, 3890, 3910, 3980, 3980, 4040, 4040, 4250, 4310, 4370, 4510, 4520, 4600, 4600, 4660, 4730, 4810, 4960, 5050, 5060, 5090, 5110, 5120, 5180, 5260, 5330, 5390, 5480, 5500, 5540, 5560, 5630, 5650, 5710, 5770, 5800, 5870, 5920, 5980, 6050, 6130, 6190, 6200, 6260, 6340, 6490, 6530, 6620, 6640, 6700, 6920, 7930, 7990, 8210, 8230, 8290, 8350, 8360, 8440, 8500, 8560, 8570, 8650, 8690, 8710, 8770, 8860, 9130, 9260, 9280, 9350, 9410, 9700, 9760, 9770, 9830, 9830, 10060, 10120, 10180, 10190, 10250, 10330, 10400, 10480, 10540, 10600, 10670, 10690, 10760, 10820, 10850, 10900, 10900, 10930, 10970, 11050, 11060, 11180, 11210, 11270, 11290, 11350, 11350, 11360, 11410, 11500, 11500, 11720, 11800, 11860, 11860, 11920, 11930, 11990, 12050, 12130, 12220, 12260, 12260, 12280, 12280, 12340, 12340, 12350, 12350, 12430, 12430, 12470, 12470, 12490, 12620, 12620, 12640, 12760, 12760, 12770, 12770, 12830, 12830, 12850, 12920, 12920, 12970, 13060, 13420, 13420, 13810, 13870, 13870, 13880, 13940};
int statusList[231] = {8, 9, 49, 63, 75, 75, 78, 83, 82, 89, 74, 99, 75, 74, 100, 60, 57, 102, 50, 48, 44, 39, 37, 32, 29, 103, 19, 18, 104, 17, 14, 13, 11, 103, 12, 104, 25, 47, 49, 103, 64, 67, 84, 85, 89, 90, 99, 91, 98, 93, 92, 92, 88, 93, 85, 94, 84, 80, 95, 78, 97, 72, 100, 69, 68, 101, 61, 102, 59, 103, 57, 49, 104, 47, 41, 106, 40, 36, 34, 25, 110, 24, 13, 116, 9, 118, 8, 120, 122, 10, 121, 17, 124, 127, 16, 15, 17, 27, 37, 75, 81, 84, 87, 88, 87, 86, 82, 81, 78, 77, 62, 60, 41, 29, 27, 25, 24, 22, 21, 18, 17, 15, 13, 12, 11, 10, 9, 10, 9, 8, 9, 10, 19, 31, 89, 94, 93, 87, 77, 55, 48, 22, 17, 16, 11, 10, 11, 25, 34, 78, 80, 121, 118, 117, 79, 116, 112, 110, 108, 107, 105, 104, 103, 102, 100, 97, 92, 91, 86, 83, 82, 78, 81, 80, 79, 76, 79, 78, 75, 74, 73, 79, 71, 70, 78, 79, 69, 68, 67, 78, 65, 79, 64, 61, 58, 55, 78, 75, 54, 71, 53, 31, 42, 25, 39, 11, 18, 10, 16, 9, 10, 17, 11, 31, 20, 38, 21, 51, 31, 33, 52, 41, 42, 51, 50, 41, 39, 9, 16, 1, 1};
// End Automatic Code

/*
Button Guide
0 - 5U - Forklift Up
1 - 5D - Forklift Down
2 - 6U - Toggle Max Speed
3 - 6D - Reverse Toggle
4 - 7L - Autonomous Task
5 - 7R - PTSD
6 - 8D - Start Debug Stream
7 - 8R - Stop All Movement (only when debug is enabled)
8 - 8U - Start Recording (only when debug is enabled)
9 - 8L - PTSD 2

*/
//ptsd open
bool ptsdOpen = false;
//second ptsd open
bool ptsd2Open = false;
bool readButton[10] = {false, false, false, false, false, false, false, false, false, false};
bool lastButton[10] = {false, false, false, false, false, false, false, false, false, false};
// Is autonomous task active
bool autoActive = false;
// Multiply speed for slow mode
float speedAdj = 1.0;
// Debug Mode Enable or Disable
bool debugMode = false;
// Forklift Lock (unused backup code)
// bool forkliftLockUp = false;
// Debug Stream
bool debugStreamOn = false;
// For integer to string conversion
string intAsString = "";
int intToConvert = 0;
// Joystick Values
int joystickL = 0;
int joystickR = 0;
// Reverse toggle
bool reversed = false;
// Currently recording for autonomous task
bool autoRecord = false;
// Autonomous Task Data
// Event Name
// Timing
// Int Status
string timing = "";
// Step Of Autonomous Task At
int taskStepAt = 0;
// Autonomous Task Recording Stuff
int lastL = 0;
int lastR = 0;
// Strings for converting
string timerString = "";
// Autonomous Task Cancel Check
bool lastCancel = false;
bool thisCancel = false;

task main()
{
	clearDebugStream();
	motor[ptsd] = -10;
	motor[ptsd2] = -20;
	while (true){
		if (vexRT[Btn7L]){
			thisCancel = true;
		}
		else{
			thisCancel = false;
		}
		//Fixed autonomous task cancel
		if (lastCancel == false && thisCancel){
			if (autoActive){
				autoActive = false;
				writeDebugStreamLine("Autonomous Task Cancel");
			}
		}
		if (lastCancel != thisCancel){
			lastCancel = thisCancel;
		}
		if (autoActive == false){
			// Read all of the buttons
			if (vexRT[Btn5U]){readButton[0] = true;}
			else{readButton[0] = false;}
			if (vexRT[Btn5D]){readButton[1] = true;}
			else{readButton[1] = false;}
			if (vexRT[Btn6U]){readButton[2] = true;}
			else {readButton[2] = false;}
			if (vexRT[Btn6D]){readButton[3] = true;}
			else{readButton[3] = false;}
			if (vexRT[Btn7L]){readButton[4] = true;}
			else{readButton[4] = false;}
			if (vexRT[Btn7R]){readButton[5] = true;}
			else{readButton[5] = false;}
			if (vexRT[Btn8D]){readButton[6] = true;}
			else{readButton[6] = false;}
			if (vexRT[Btn8R]){readButton[7] = true;}
			else{readButton[7] = false;}
			if (vexRT[Btn8U]){readButton[8] = true;}
			else{readButton[8] = false;}
			if (vexRT[Btn8L]){readButton[9] = true;}
			else{readButton[9] = false;}
			joystickL = vexRT[Ch3];
			joystickR = vexRT[Ch2];
			if (joystickL < 10 && joystickL > 10){
				joystickL = 0;
			}
			if (joystickR < 10 && joystickR > 10){
				joystickR = 0;
			}
			//Recording Autonomous Task
			if (lastL != joystickL){
				if (autoRecord){
					writeDebugStream(", 'L', ");
					intToConvert = time1[T1];
					sprintf(intAsString, "%d", intToConvert);
					writeDebugStream(intAsString);
					writeDebugStream(", ");
					intToConvert = joystickL;
					sprintf(intAsString, "%d", intToConvert);
					writeDebugStream(intAsString);
					lastL = joystickL;
				}
			}
			if (lastR != joystickR){
				if (autoRecord){
					writeDebugStream(", 'R', ");
					intToConvert = time1[T1];
					sprintf(intAsString, "%d", intToConvert);
					writeDebugStream(intAsString);
					writeDebugStream(", ");
					intToConvert = joystickR;
					sprintf(intAsString, "%d", intToConvert);
					writeDebugStream(intAsString);
					lastR = joystickR;
				}
			}

			if (autoRecord){
				intToConvert = time1[T1];
				sprintf(intAsString, "%d", intToConvert);
				timing = intAsString;

				if (readButton[0] != lastButton[0]){
					if (readButton[0]){
						writeDebugStream(", 'B0', ");
						writeDebugStream(timing);
						writeDebugStream(", true");
					}
					else{
						writeDebugStream(", 'B0', ");
						writeDebugStream(timing);
						writeDebugStream(", false");
					}
				}
				if (readButton[1] != lastButton[1]){
					if (readButton[1]){
						writeDebugStream(", 'B1', ");
						writeDebugStream(timing);
						writeDebugStream(", true");
					}
					else{
						writeDebugStream(", 'B1', ");
						writeDebugStream(timing);
						writeDebugStream(", false");
					}
				}
				if (readButton[2] != lastButton[2]){
					if (readButton[2]){
						writeDebugStream(", 'B2', ");
						writeDebugStream(timing);
						writeDebugStream(", true");
					}
					else{
						writeDebugStream(", 'B3', ");
						writeDebugStream(timing);
						writeDebugStream(", false");
					}
				}
				if (readButton[3] != lastButton[3]){
					if (readButton[1]){
						writeDebugStream(", 'B3', ");
						writeDebugStream(timing);
						writeDebugStream(", true");
					}
					else{
						writeDebugStream(", 'B3', ");
						writeDebugStream(timing);
						writeDebugStream(", false");
					}
				}
				if (readButton[4] != lastButton[4]){
					if (readButton[4]){
						writeDebugStream(", 'B4', ");
						writeDebugStream(timing);
						writeDebugStream(", true");
					}
					else{
						writeDebugStream(", 'B4', ");
						writeDebugStream(timing);
						writeDebugStream(", false");
					}
				}
				if (readButton[5] != lastButton[5]){
					if (readButton[5]){
						writeDebugStream(", 'B5', ");
						writeDebugStream(timing);
						writeDebugStream(", true");
					}
					else{
						writeDebugStream(", 'B5', ");
						writeDebugStream(timing);
						writeDebugStream(", false");
					}
				}
				if (readButton[9] != lastButton[9]){
					if (readButton[9]){
						writeDebugStream(", 'B9', ");
						writeDebugStream(timing);
						writeDebugStream(", true");
					}
					else{
						writeDebugStream(", 'B9', ");
						writeDebugStream(timing);
						writeDebugStream(", false");
					}
				}
			}
			// Output to Debug Stream
			if (debugStreamOn){
				intToConvert = vexRT[Ch3];
				sprintf(intAsString, "%d", intToConvert);
				writeDebugStream("Joystick Left: ");
				writeDebugStream(intAsString);
				intToConvert = vexRT[Ch2];
				sprintf(intAsString, "%d", intToConvert);
				writeDebugStream(", Joystick Right: ");
				writeDebugStream(intAsString);
				writeDebugStream(", autoActive: ");
				if (autoActive){intAsString = "true";}
				else {intAsString = "false";}
				writeDebugStream(intAsString);
				writeDebugStream(", speedAdj: ");
				sprintf(intAsString, "%d", speedAdj);
				writeDebugStreamLine(intAsString);
			}
		}
		//Read Autonomous Task
		if (autoActive){
			if (timingList[taskStepAt] < time1[T1]){
				writeDebugStreamLine(eventsList[taskStepAt]);
				if (eventsList[taskStepAt] == "L"){
					joystickL = statusList[taskStepAt];
				}
				if (eventsList[taskStepAt] == "R"){
					joystickR = statusList[taskStepAt];
				}
				if (eventsList[taskStepAt] == "B0"){
					if(statusList[taskStepAt] == 1){readButton[0] = true;}
					else{readButton[0] = false;}
				}
				if (eventsList[taskStepAt] == "B1"){
					if(statusList[taskStepAt] == 1){readButton[1] = true;}
					else{readButton[1] = false;}
				}
				if (eventsList[taskStepAt] == "B2"){
					if(statusList[taskStepAt] == 1){readButton[2] = true;}
					else{readButton[2] = false;}
				}
				if (eventsList[taskStepAt] == "B3"){
					if(statusList[taskStepAt] == 1){readButton[3] = true;}
					else{readButton[3] = false;}
				}
				if (eventsList[taskStepAt] == "B4"){
					if(statusList[taskStepAt] == 1){readButton[4] = true;}
					else{readButton[4] = false;}
				}
				if (eventsList[taskStepAt] == "B5"){
					if(statusList[taskStepAt] == 1){readButton[5] = true;}
					else{readButton[5] = false;}
				}
				if (eventsList[taskStepAt] == "B9"){
					if(statusList[taskStepAt] == 1){readButton[9] = true;}
					else{readButton[5] = false;}
				}
				taskStepAt += 1;
				if (taskStepAt == autoTaskLength){
					writeDebugStreamLine("Auto Task Done");
					autoActive = false;
				}
			}
		}
		// Drive Motors
		if (reversed){
			motor[right] = floor(joystickL*speedAdj);
			motor[left] = floor(joystickR*speedAdj);
		}
		else{
			motor[left] = floor(joystickL*speedAdj);
			motor[right] = floor(joystickR*speedAdj);
		}
		// Forklift Up
		if (readButton[0]){
			motor[forklift] = 90;
		}
		// Forklift Down
		if (readButton[1]){
			motor[forklift] = -90;
		}
		if (readButton[0] == false && readButton[1] == false){
			motor[forklift] = 0;
		}
		// Toggle Slow Mode
		if (readButton[2] && (lastButton[2] == false)){
			if (speedAdj > 0.9){
				speedAdj = 0.25;
			}
			else{
				speedAdj = 1.0;
			}
		}
		// Reverse Controls
		if (readButton[3] && (lastButton[3] == false)){
			speedAdj = speedAdj * -1;
		}
		// Autonomous Task Toggle
		if (readButton[4] && (lastButton[4] == false)){
			if (autoActive){
				autoActive = false;
				writeDebugStreamLine("Autonomous Task Cancel");
			}
			else{
				clearDebugStream();
				writeDebugStreamLine("Autonomous Task Start");
				autoActive = true;
				clearTimer(T1);
				taskStepAt = 0;
			}
		}
		//
		// Debug Stuff
		if (debugMode){
			// OH NOWO! I MADE AN UWUPSIE BUTTON
			if (readButton[7]){
				motor[forklift] = 0;
				motor[left] = 0;
				motor[right] = 0;
				motor[ptsd] = -20;
				break;
			}
			if (readButton[6] && (lastButton[6] == false)){
				if (debugStreamOn){
					debugStreamOn = false;
				}
				else {
					if (autoActive == false && autoRecord == false){
						debugStreamOn = true;
						clearDebugStream();
					}
				}
			}
			if (readButton[8]){
				debugStreamOn = false;
				clearTimer(T1);
				clearDebugStream();
				autoRecord = true;
			}

		}
		// Open and close PTSD
		if (readButton[5] && (lastButton[5] == false)){
			if (ptsdOpen){
				ptsdOpen = false;
				motor[ptsd] = -10;
			}
			else{
				if (ptsd2Open){
					ptsd2Open = false;
					motor[ptsd2] = -20;
				}
				ptsdOpen = true;
				motor[ptsd] = -127;
			}
		}
		// Open and close PTSD 2
		if (readButton[9] && (lastButton[9] == false)){
			if (ptsd2Open){
				ptsd2Open = false;
				//Closed position
				motor[ptsd2] = -20;
			}
			else{
				if (ptsdOpen){
					ptsdOpen = false;
					motor[ptsd] = -10;
				}
				ptsd2Open = true;
				motor[ptsd2] = -127;
			}
		}

		// Set lastButton to readButton
		lastButton[0] = readButton[0];
		lastButton[1] = readButton[1];
		lastButton[2] = readButton[2];
		lastButton[3] = readButton[3];
		lastButton[4] = readButton[4];
		lastButton[5] = readButton[5];
		lastButton[6] = readButton[6];
		lastButton[7] = readButton[7];
		lastButton[8] = readButton[8];
		lastButton[9] = readButton[9];
		wait1Msec(10);
	}

}
